### ISSUE TITLE
Error on player statistics

### ISSUE THREAD

**Issue by yukasung** [ThemeBoy/SportsPress#409] opened 2021-05-18 07:05 UTC
I got an error this below.
Notice: Trying to get property 'term_id' of non-object
<img width="944" alt="Screen Shot 2021-05-18 at 2 03 57 PM" src="https://user-images.githubusercontent.com/7720293/118606839-105db280-b7e2-11eb-8b57-c7e8966678c7.png">

**Comment by savvasha** [comment] 2021-05-18 07:19
Hi @yukasung,

Is this happening to all your players? What if you create a new player?

**Comment by yukasung** [comment] 2021-05-18 07:39
It was happening to all players but it works well if I create a new player.

**Comment by yukasung** [comment] 2021-05-18 07:43
Error is gone when I selected the club to the player statistics.
<img width="770" alt="Screen Shot 2021-05-18 at 2 41 08 PM" src="https://user-images.githubusercontent.com/7720293/118611558-2b7ef100-b7e7-11eb-8b5e-38abe7aed825.png">
<img width="769" alt="Screen Shot 2021-05-18 at 2 41 21 PM" src="https://user-images.githubusercontent.com/7720293/118611590-38034980-b7e7-11eb-9ad2-07c504e92a45.png">

**Comment by savvasha** [comment] 2021-05-18 08:05
Unfortunately I am not able to reproduce this issue...
![image](https://user-images.githubusercontent.com/6088209/118614907-e350d600-b7c8-11eb-9ec9-50c97e6ccb1e.png)
![image](https://user-images.githubusercontent.com/6088209/118614977-f499e280-b7c8-11eb-9c77-77dbda48c930.png)

**Comment by savvasha** [comment] 2021-05-18 08:06
How did you create the players that have this issue?

**Comment by yukasung** [comment] 2021-05-18 08:23
The error occurs when I used "Duplicate Page" plugin to create a new player.

**Comment by savvasha** [comment] 2021-05-18 08:36
Then it seems to be an issue with how this plugin duplicates the players data.

**Comment by yukasung** [comment] 2021-05-18 08:39
I used this plugin because I create more than 200 players for two leagues on the demo website.

**Comment by yukasung** [comment] 2021-05-18 08:41
Is it impossible you will resolve this issue?

**Comment by savvasha** [comment] 2021-05-18 09:23
SportsPress PRO has a module called Duplicator that can do exactly what you want. https://www.themeboy.com/sportspress-extensions/duplicator/

I am closing down this because it is not a SportsPress issue.

**Closed by savvasha** 2021-05-18 09:23 UTC
